name: Run CUDA Code 
on:
    workflow_dispatch

jobs:
    run-script:
        runs-on:
            group: unifac-runners-serial
        steps:
        - uses: actions/checkout@v3
        - name: Export Paths
          run: |
            export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
            export LD_LIBRARY_PATH=/usr/local/cuda/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
        - uses: Jimver/cuda-toolkit@v0.2.23
          id: cuda-toolkit
          with:
            cuda: '12.5.0'
        - name: Print Version
          run: |
            echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
        - name: Print Path
          run: |
            echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
        - name: View potential installation locaiton
          run: |
            ls /usr/local/
        
        - name: Compile CUDA code
          run: |
            nvcc unifac_i.cu -o unifac -l cublas