name: Run CUDA Code 
on:
    workflow_dispatch

jobs:
  run_python_tests:
    runs-on:
      group: unifac-runners
    container:
      image: nvcr.io/nvidia/cuda:12.9.0-devel-ubuntu22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync --locked --all-extras --dev
        working-directory: ./src
      - name: Run Tests
        run: uv run pytest
        working-directory: ./src
      - run: nvcc unifac_i.cu -o unifac-model -l cublas
        working-directory: ./src
      - run: |
          uv run ./utils/create_config.py
          ls
        working-directory: ./src
      - run: |
          ./unifac-model config.txt
        working-directory: ./src

