name: Run Nvidia-SMI

on:
    workflow_dispatch

jobs:
    run-script:
        runs-on:
            group: unifac-runners
        steps:
        - name: Run nvidia smi
          run: |
            nvidia-smi