name: Run CUDA Code 
on:
    workflow_dispatch

jobs:
  run_python_tests:
    runs-on:
      group: ubuntu:latest
    container:
      image: nvcr.io/nvidia/cuda:12.4.0-devel-ubuntu22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync --locked --all-extras --dev
        working-directory: ./src
      - name: Run Tests
        run: uv run pytest
        working-directory: ./src
      - run: nvcc unifac_i.cu -o unifac-model -l cublas
        working-directory: ./src
      - run: |
          uv run ./utils/create_config.py
          ls
        working-directory: ./src
      - uses: actions/upload-artifact@v4
        with:
            name: unifac-executable
            path: unifac-model
  run_cuda:
    runs-on:
      group: unifac-runners
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: unifac-executable
        path: ./src/unifac-model

    - run: |
        ./unifac-model config.txt
      working-directory: ./src
    needs: run_python_tests

