name: Run CUDA Code 
on:
    workflow_dispatch

jobs:
  run-script:
      runs-on: ubuntu-latest
      container:
        image: nvcr.io/nvidia/cuda:12.0.1-devel-ubuntu22.04
      steps:
      - uses: actions/checkout@v3
    #   - uses: Jimver/cuda-toolkit@v0.2.23
    #     id: cuda-toolkit
    #     with:
    #       cuda: '12.5.0'

    #   - run: |
    #       echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"

    #   - run: |
    #       echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"

      - run: nvcc unifac_i.cu -o unifac -l cublas
      - uses: actions/upload-artifact@v4
        with:
            name: unifac-executable
            path: unifac