name: Run CUDA Code 
on:
    workflow_dispatch

jobs:
  compile:
      runs-on: ubuntu-latest
      container:
        image: nvcr.io/nvidia/cuda:12.0.1-devel-ubuntu22.04
      steps:
      - uses: actions/checkout@v3
      - run: nvcc unifac_i.cu -o unifac -l cublas
      - uses: actions/upload-artifact@v4
        with:
            name: unifac-executable
            path: unifac
  execute:
    runs-on:
      group: unifac-runners 
    steps:
    - name: Download executable
      uses: actions/download-artifact@v4
      with:
        name: unifac-executable
    - run: ./unifac
